### ISSUE TITLE
编译通过后，如何运行？

### ISSUE THREAD

**Issue by githubchenwei** [xeniumlee/iotedge.skynet#2]
首先，目录中没有bin目录，首先建立bin目录并在该目录下建立prebuilt文件夹，将openssl和snap7编译好的库文件放到其中。
        编译顺利通过，之后通过release.sh脚本打包生成文件，利用install.sh安装到系统目录中。在执行上述脚本时是否要带参数，目前编译通过，运行没成功。麻烦指导下

**Comment by xeniumlee** [comment]
See README
